name: release-app

on:
  push:
    tags:
      - '*'

jobs:
  release-app:
    name: Job for building and releasing Plumptech React application
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo source code
        uses: actions/checkout@v3
      - name: Install Node.js v14
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: Create env file
        run: |
          touch .env.local
          echo "REACT_APP_API_ENDPOINT=${{ secrets.REACT_APP_API_ENDPOINT }}" >> .env.local
          echo "REACT_APP_APP_KEY=${{ secrets.REACT_APP_APP_KEY }}" >> .env.local
          cat .env.local
      - name: Install app dependencies
        run: npm ci
      - name: Build application
        run: |
          npm run build --if-present \
          && tar -zcvf plumptech.tar.xz ./build
      - name: Release production-ready application
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: plumptech.tar.xz
